FROM python:3.12.2-slim

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt


COPY *.sh .
COPY *.py .
COPY *.html .
COPY . .


EXPOSE 5000

CMD ["python", "test_assign3.py"]
#CMD ["sleep","infinity"]
#["pytest","-s","-vv","test_assign3.py"]
#["pytest","-vv","test_assign3.py"]
