name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker compose -f "tests/docker-compose-tests.yml" up -d --build

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      #with:
       # terraform_version:  "1.1.7"

    - name: Initialize the Terraform Configuration
      run: terraform init

    - name: Run Terraform Plan
      run: terraform plan

    - name: Run Terraform Apply
      run: terraform apply --auto-approve

    - name: Test with Pytest
      run: docker exec tests-app-1 bash -c "pytest"